### ISSUE TITLE
PrimeVue v4

### ISSUE THREAD

**Issue by incon** [connorabbas/primevue-auth-starter#1]
How much of a breaking change will PrimeVue v4 be?

**Comment by connorabbas** [comment]
Biggest changes will be the theming and the light/dark mode implementation. It also looks like they are not recommending the use of PrimeFlex anymore, so that will have to be replaced with Tailwind utilities instead.

Once the official v4 major release is ready (they currently have a couple of release candidates) I plan on doing a Laravel 11 and PrimeVue 4 branch, which will eventually become the main/master for this project.

Thanks for your interest in the project 👍
